#define GML_ENUM                             1
#define GML_LBRACKET                         2
#define GML_RBRACKET                         3
#define GML_STRING                           4
#define GML_EQUAL                            5
#define GML_INT                              6
#define GML_OBJECT                           7
#define GML_COLUMN                           8
#define GML_ARRAY                            9
#define GML_LTAG                            10
#define GML_RTAG                            11
#define GML_BOOL                            12
#define GML_FLOAT                           13
#define GML_STRINGVALUE                     14
#define GML_TAG                             15
#define GML_PLUSINF                         16
#define GML_MINUSINF                        17
#define GML_TYPEBOOL                        18
#define GML_TYPEUINT                        19
#define GML_TYPEINT                         20
#define GML_TYPEUFLOAT                      21
#define GML_TYPEFLOAT                       22
#define GML_TYPEFLOAT2                      23
#define GML_TYPEFLOAT3                      24
#define GML_TYPEFLOAT4                      25
#define GML_TYPESTRING                      26
#define GML_TYPEEXPRESSION                  27
#define GML_NONZERO                         28
#define GML_REF                             29
